/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.lon;

import com.lon.ipc.IDdwIpc;
import com.lon.ipc.IDdwMessageHandler;
import picocli.CommandLine;

import javax.inject.Inject;

public class App  {

    IDdwMessageHandler handler;
    IDdwIpc ipc;
    static String[] args;

    @Inject
    public App(IDdwMessageHandler handler, IDdwIpc ipc) {
        this.handler = handler;
        this.ipc = ipc;
    }

    public void start() {
        var exitCode = new CommandLine(new GenThumbs()).execute(args);

        if (exitCode != 0) {
            System.exit(exitCode);
        }

    }

    public static void main(String[] args) {
        var app = DaggerAppComponent.create().app();
        App.args = args;
        app.start();

    }

}
